onEvent('block.registry', event => {
  event.create('crushed_deepslate', 'falling')
    .material('dirt')
    .hardness(0.5)
    .displayName('Crushed Deepslate')
    .tagBlock('minecraft:mineable/shovel')
    .dustColor(color.GRAY)
 })
 onEvent('block.registry', event => {
  event.create('radiated_stone')
    .material('stone')
    .hardness(0.5)
    .displayName('Radiated Stone')
    .tagBlock('minecraft:needs_iron_tool')
    .dustColor(color.GRAY)
})
 onEvent('block.registry', event => {
  event.create('bronze_block')
    .material('iron')
    .hardness(0.5)
    .displayName('Bronze_Block')
    .tagBlock('minecraft:needs_iron_tool')
    .dustColor(color.GOLD)
})