// Listen to item registry event
onEvent('item.registry', event => {
  event.create('mechanic'),
    event.create('doctor'),
	event.create('doctor_3'),
	event.create('doctor_10'),
	event.create('doctor_20'),
	event.create('doctor_30'),
	event.create('doctor_40'),
	event.create('doctor_50'),
    event.create('geologist'),
    event.create('engineer'),
	event.create('engineer_3'),
	event.create('engineer_10'),
	event.create('engineer_20'),
	event.create('engineer_30'),
	event.create('engineer_40'),
	event.create('engineer_50'),
    event.create('pilot'),
    event.create('navigator'),
	event.create('captain'),
    event.create('captain_3'),
	event.create('captain_10'),
	event.create('captain_20'),
	event.create('captain_30'),
	event.create('captain_40'),
	event.create('captain_50'),
    event.create('security_officer'),
	event.create('security_officer_3'),
	event.create('security_officer_10'),
	event.create('security_officer_20'),
	event.create('security_officer_30'),
	event.create('security_officer_40'),
	event.create('security_officer_50'),	
    event.create('chef'),
    event.create('botanist'),
    event.create('dissected_organs'),
    event.create('fire'),
    event.create('water'),
    event.create('wind'),
    event.create('earth')



})