////////////////////////
/// Made by Team AOF ///
////////////////////////


onEvent('tags.items', event => {

    const replicator = [
        'create:handheld_worldshaper',
        'create:creative_blaze_cake',
        'indrev:tank',
        'indrev:portable_charger',
        'indrev:modular_armor_helmet',
        'indrev:modular_armor_chest',
        'indrev:modular_armor_legs',
        'indrev:modular_armor_boots',
        'indrev:lazuli_flux_container_mk1',
        'indrev:lazuli_flux_container_mk2',
        'indrev:lazuli_flux_container_mk3',
        'indrev:lazuli_flux_container_mk4',
        'kibe:tank',
        'kibe:angel_ring',
        'ae2:quantum_entangled_singularity',
        'ae2:spatial_storage_cell_2',
        'ae2:spatial_storage_cell_16',
        'ae2:spatial_storage_cell_128',
        'ae2:sky_stone_tank',
        'ae2:portable_item_cell_1k',
        'ae2:portable_item_cell_4k',
        'ae2:portable_item_cell_16k',
        'ae2:portable_item_cell_64k',
        'ae2:portable_item_cell_256k',
        'ae2:portable_fluid_cell_1k',
        'ae2:portable_fluid_cell_4k',
        'ae2:portable_fluid_cell_16k',
        'ae2:portable_fluid_cell_64k',
        'ae2:portable_fluid_cell_256k',
        'ae2:item_storage_cell_1k',
        'ae2:item_storage_cell_4k',
        'ae2:item_storage_cell_16k',
        'ae2:item_storage_cell_64k',
        'ae2:item_storage_cell_256k',
        'ae2:fluid_storage_cell_1k',
        'ae2:fluid_storage_cell_4k',
        'ae2:fluid_storage_cell_16k',
        'ae2:fluid_storage_cell_64k',
        'ae2:fluid_storage_cell_256k',
        'ae2things:disk_drive_1k',
        'ae2things:disk_drive_4k',
        'ae2things:disk_drive_16k',
        'ae2things:disk_drive_64k',
        'ae2things:item_storage_cell_256k',
        'ae2things:item_storage_cell_1024k',
        'ae2things:item_storage_cell_4096k',
        'ae2things:fluid_storage_cell_256k',
        'ae2things:fluid_storage_cell_1024k',
        'ae2things:fluid_storage_cell_4096k',
        'ae2things:portable_item_cell_256k',
        'ae2things:portable_item_cell_1024k',
        'ae2things:portable_item_cell_4096k',
        'ae2things:portable_fluid_cell_256k',
        'ae2things:portable_fluid_cell_1024k',
        'ae2things:portable_fluid_cell_4096k',
        'ae2things:portable_disk_1k',
        'ae2things:portable_disk_4k',
        'ae2things:portable_disk_16k',
        'ae2things:portable_disk_64k',
        'minecraft:dragon_egg',
        'spectrum:void_bundle',
        'kibe:golden_lasso',
        'kibe:cursed_lasso',
        'kibe:diamond_lasso',
        'modern_industrialization:quantum_helmet',
        'modern_industrialization:quantum_chestplate',
        'modern_industrialization:quantum_leggings',
        'modern_industrialization:quantum_boots',
        'modern_industrialization:quantum_sword',
        'modern_industrialization:singularity',
        'create:fluid_tank',
        'create:creative_fluid_tank',
        'coxinhautilities:portable_tank_mk1',
        'coxinhautilities:portable_tank_mk2',
        'coxinhautilities:portable_tank_mk3',
        'coxinhautilities:portable_tank_mk4',
        'coxinhautilities:portable_tank_mk5',
        'automobility:automobile_engine',
    ];

    replicator.forEach((item) => {
        event.add('modern_industrialization:replicator_blacklist', item)
    });

});
